plugins {
    id 'base'
}

allprojects {
    group = rootProject.maven_group
    version = rootProject.mod_version
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'maven-publish'

    base {
        // Set up a suffixed format for the mod jar names, e.g. `example-neoforge`.
        archivesName = "$rootProject.archives_name-$project.name"
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(25)
        }
        withSourcesJar()
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 25
        it.options.encoding = 'UTF-8'
        it.options.compilerArgs += ['-Xmaxerrs', '1000', '-Xmaxwarns', '1000']
    }

    repositories {
        mavenCentral()
        maven { url = 'https://maven.blamejared.com/' }
        maven { url = 'https://maven.theillusivec4.top/' }
    }

    // Configure Maven publishing.
    publishing {
        publications {
            mavenJava(MavenPublication) {
                artifactId = base.archivesName.get()
                from components.java
            }
        }

        // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
        repositories {
            // Add repositories to publish to here.
            // Notice: This block does NOT have the same function as the block in the top level.
            // The repositories here will be used for publishing your artifact, not for
            // retrieving dependencies.
        }
    }
}
